[package]
name = "mel_spec"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Mel spectrograms aligned to the results from the whisper.cpp, pytorch and librosa reference implementations and suited to streaming audio."
repository = "https://github.com/wavey-ai/mel_spec"
readme = "README.md"

[dependencies]
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
num = "0.4.1"
rustfft = "6.1.0"
